bush:
  - align: 
      distance: [0.3, 100]
    name: Ficus Bush Trimmed
    path: retrieved/mesh/de5510c6-2112-4b19-8c05-f934db0440a2.glb
    rescale:
      height: [0.1, 1.0]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Holly Bush
    path: retrieved/mesh/ce9df37e-696a-4386-a1b6-228b97994c21.glb
    rescale:
      height: [0.1, 1.0]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Holly Bush Trimmed
    path: retrieved/mesh/cb1f02cf-abc6-46cf-8cc4-8ac03acbfefb.glb
    rescale:
      height: [0.1, 1.0]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Button Bush Large
    path: retrieved/mesh/a0176016-f9a2-4595-ab78-6a2debf2916d.glb
    rescale:
      height: [0.1, 1.0]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Button Bush Medium
    path: retrieved/mesh/2b2f690b-f4e2-416a-8673-5ed335ea708a.glb
    rescale:
      height: [0.1, 1.0]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Cranberry Bush Large
    path: retrieved/mesh/076d9a82-a080-4791-aac6-4d0f06076341.glb
    rescale:
      height: [0.1, 1.0]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Cranberry Bush Large Variation
    path: retrieved/mesh/73c642ea-1ca2-4648-8dba-1fd5e404fb5b.glb
    rescale:
      height: [0.1, 1.0]
    type: mesh
cone:
  - align: 
      distance: [0.3, 100]
    name: Traffic Cone
    path: retrieved/mesh/c40f8c59-9987-4560-aa74-b225f418dfff.glb
    rescale:
      height: [0.5, 1.0]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Traffic Cone
    path: retrieved/mesh/956c7a35-5529-4246-9fdb-c90b9e4a1b7a.glb
    rescale:
      height: [0.5, 1.0]
    type: mesh
sign:
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Danger Road Sign
    path: retrieved/mesh/911cb13c-a417-4511-8de1-294e4553d0ae.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: No Parking Road Sign
    path: retrieved/mesh/4ec521d8-8cb7-41fb-ad9b-b597b0a7ce9c.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Only Straight Road Sign
    path: retrieved/mesh/f164900d-2e42-4ce9-8e84-5f5d34919321.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Roundabout Road Sign
    path: retrieved/mesh/60765b4c-28ac-4148-ac17-d8dd7c36814b.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Road Sign Stop French Standard (AB3)
    path: retrieved/mesh/8246f271-d4c8-4282-b7e0-6c9799a285ce.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Road Sign Speed French Std (B14)
    path: retrieved/mesh/2134750f-42a1-4394-a99d-fda90f363ce0.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Road Sign No Parking French Std (B6a1)
    path: retrieved/mesh/df1764c1-f6a2-4cac-a72b-88bc4a076f11.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Road Sign No Stop French Std (B6d)
    path: retrieved/mesh/0ce75741-d470-40b9-a3cb-a800440d52d8.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 1.5708
      distance: [0.5, 100]
    name: Road Sign Direction French Std (B21c)
    path: retrieved/mesh/e6796407-f3c4-470b-a283-d5dc4c08bee8.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
street_lamp:
  - align: 
      angle: 0.0
      distance: [0.5, 100]
    name: Street Lamp
    path: retrieved/mesh/86b1e4bd-87c3-4b01-bdfe-fd7330c8d758.glb
    rescale:
      height: [2.5, 3.0]
    type: mesh
  - align: 
      angle: 0.0
      distance: [0.5, 100]
    name: Street Light
    path: retrieved/mesh/bcefc510-c220-418d-819b-051b7ffebfc0.glb
    rescale:
      height: [2.5, 3.0]
    type: mesh
  - align: 
      angle: 0.0
      distance: [0.5, 100]
    name: Street Light
    path: retrieved/mesh/ba4ef7c6-3dec-4415-b8cb-794f1af4a2ff.glb
    rescale:
      height: [2.5, 3.0]
    type: mesh
  - align: 
      angle: 0.0
      distance: [0.5, 100]
    name: Street Light
    path: retrieved/mesh/25f7eef0-7da4-4337-8741-f7fbc33fd036.glb
    rescale:
      height: [2.5, 3.0]
    type: mesh
  - align: 
      angle: 0.0
      distance: [0.5, 100]
    name: Modern Street Light
    path: retrieved/mesh/a5e9ffeb-089d-4701-8446-b94ea27a7b5a.glb
    rescale:
      height: [2.5, 3.0]
    type: mesh
traffic_light:
  - align: 
      angle: 0.0
      distance: [0.5, 100]
    name: Traffic Light
    path: retrieved/mesh/25f55577-cea8-4f58-8ca1-523f64662717.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 0.0
      distance: [0.3, 100]
    name: Traffic Light 01
    path: retrieved/mesh/1ce4b2c6-09d2-4383-9d94-937d7d2f9a99.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
  - align: 
      angle: 0.0
      distance: [0.3, 100]
    name: Traffic Light 03
    path: retrieved/mesh/496c7f23-6259-4154-b01d-36c4884241eb.glb
    rescale:
      height: [2.0, 5.0]
    type: mesh
tree:
  - align: 
      distance: [0.3, 100]
    name: Broadleaf Dense Tree Adult
    path: retrieved/mesh/599b0e84-d7f4-44ab-b26f-1572f49d2e65.glb
    rescale:
      height: [2.5, 4.5]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Tree Siberian Pine A2
    path: retrieved/mesh/ddde80ce-5365-4c01-bb0e-fc898894536e.glb
    rescale:
      height: [2.5, 4.5]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Tree Alder A1 Large
    path: retrieved/mesh/d91fc43e-8021-4517-b091-d562b6216a82.glb
    rescale:
      height: [2.5, 4.5]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Tree Alder A6 Large
    path: retrieved/mesh/07eafd56-a304-4665-878b-500965d3a4de.glb
    rescale:
      height: [2.5, 4.5]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Tree Alder A7 Large
    path: retrieved/mesh/4bfaa14e-01d3-4919-b275-5eba894b187f.glb
    rescale:
      height: [2.5, 4.5]
    type: mesh
  - align: 
      distance: [0.3, 100]
    name: Tree PineSiberian B1
    path: retrieved/mesh/10f78da9-0fef-4b52-8b40-dfab39fd1bc7.glb
    rescale:
      height: [2.5, 4.5]
    type: mesh
  # - align: 
  #     distance: [0.3, 100]
  #   name: Jacaranda Tree
  #   path: retrieved/mesh/5e5b2685-3dbe-4d9b-830a-224a0c0faae4.glb
  #   rescale: 1.0
  #   type: mesh
  - align: 
      distance: [0.3, 100]
    name: Oak Tree
    path: retrieved/mesh/5a80112a-73d8-4180-9f1c-4cdc7495d030.glb
    rescale:
      height: [2.5, 4.5]
    type: mesh
bench:
  - align: 
      distance: [0.5, 100]
      angle: 1.5708
    name: Park Bench
    path: retrieved/mesh/68f2b6d8-576e-4b81-a973-095846a70d62.glb
    rescale: 
      height: [0.5, 1.0]
  - align:
      distance: [0.5, 100]
      angle: 0.0
    name: City Bench
    path: retrieved/mesh/ba8452a5-f65a-499e-b13c-a79d33abdef2.glb
    rescale:
      height: [0.5, 1.0]