natural:
  natural=tree: tree:random
  natural=scrub: bush:random

amenities:
  highway=street_lamp: street_lamp:same
  amenity=bench: bench:same
  # amenity=shelter: shelter:random
  # amenity=telephone: telephone:same
  # amenity=waste_basket: trash_can:same
  # amenity=recycling: trash_can:same